apiVersion: v1
kind: Namespace
metadata:
  name: spark
  labels:
    type: environment
    environment: spark
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: spark
  name: spark-sa
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: spark
  name: spark-sa-rb
subjects:
- kind: User
  name: system:serviceaccount:spark:spark-sa
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io